apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"ingress-nginx-controller","namespace":"ingress-nginx"},"spec":{"ports":[{"name":"http","nodePort":31080,"port":80,"targetPort":80},{"name":"https","nodePort":31443,"port":443,"targetPort":443}],"selector":{"app.kubernetes.io/component":"controller","app.kubernetes.io/name":"ingress-nginx"},"type":"NodePort"}}
  creationTimestamp: "2025-01-14T16:53:53Z"
  name: ingress-nginx-controller
  namespace: ingress-nginx
  resourceVersion: "132500"
  uid: c0902611-04a4-4fa1-973e-e4ab2c9651f0
spec:
  clusterIP: 10.43.188.185
  clusterIPs:
  - 10.43.188.185
  externalTrafficPolicy: Cluster
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: http
    nodePort: 31080
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 31443
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app.kubernetes.io/component: controller
    app.kubernetes.io/name: ingress-nginx
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
